#!/bin/bash

mkdir -p $HOME/workspace
cd $HOME/workspace

export GIT_DIR=./.git
git init .
git pull $HOME/repo.git
git checkout master

go build -o $HOME/{{GOLANG_EXECUTABLE}} > ../lastbuild.stdout 2> ../lastbuild.stderr
